version: '2.0'
services:
  spike-client:
    container_name: spike-client
    image: spikeproj/spike-client:latest
    ports:
      - '4200:4200' # Change it if you want
    build: .
    volumes:
      - ./logs:/usr/src/app/logs
    restart: always
